spring.application.name=connect4-security
server.port=9001
jwt.secret=76e8b4800d91ac3a6646063b9ec43cc209f8536c738d9ff5030813af3580a126
jwt.expiration=900
services.security-service.url=localhost:9001
spring.datasource.url=jdbc:postgresql://localhost:5432/connect4
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest