spring.application.name=connect4-statistics
server.port=9005
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.datasource.url=jdbc:postgresql://localhost:5432/connect4
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
services.security-service.url=localhost:9001
jwt.secret=76e8b4800d91ac3a6646063b9ec43cc209f8536c738d9ff5030813af3580a126
jwt.expiration=900S