name: CI
on: push
jobs:
  build-all-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [connect4-common, connect4-chat, connect4-bot, connect4-friendlist, connect4-gaming, connect4-gateway, connect4-matchmaking,
          connect4-security, connect4-statistics]
    
    defaults:
      run:
        working-directory: ./${{ matrix.project }}

    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build ${{ matrix.project }} with Gradle
        run: ./gradlew clean build -x test
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.project }}
          path: ./${{ matrix.project }}/build/libs/*.jar

